### ISSUE TITLE
Scope of the project and tasks

### ISSUE THREAD

**Issue by victorscher** [victorscher/simple-todo#1]
**Tasks**
- [ ] Finish project scope
- [ ] Model use cases
- [ ] Define technology stack
- [ ] Specify the principal features

---

**Database**
- [ ] Model database diagram
- [ ] Build database structure

---

**Front-end**

- [ ] Build interface

---

**Back-end** 

- [ ] Build a login system

**Comment by victorscher** [comment]
**Features**
- [ ] Tasks
  - [ ] Register a new task
    - [ ] Set deadline
    - [ ] Set a priority
  - [ ] Delete a task 
    - [ ] Permanently delete
    - [ ] Move to trash

--- 

**Stack of Technologies**
- PHP
  - CodeIginiter
- HTML
- CSS 
    - Bulma
- JavaScript
- MySQL
